name: TimeTools
version: 0.1.0
main: com.github.joelvaningen.timetools.TimeTools
api-version: 1.21.1
commands:
  time:
    description: Forward time without resetting local difficulty
    usage: /<command> [time | clocktime | tick amount]